# Generated by Django 2.2.6 on 2019-10-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videovoteuser',
            name='status',
            field=models.CharField(choices=[('0', 'Dislike'), ('1', 'Like')], default='1', max_length=1, verbose_name='status'),
        ),
    ]
