# Generated by Django 2.2.6 on 2019-10-16 03:34

from django.db import migrations, models
import videos.models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_videovoteuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='title1',
            field=models.BinaryField(default=0, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='video',
            name='videofile',
            field=models.FileField(null=True, upload_to=videos.models.get_upload_path, verbose_name=''),
        ),
    ]
