# Generated by Django 2.2.5 on 2019-10-01 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20190930_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='adddate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Add Time'),
        ),
    ]
