# Generated by Django 2.2.6 on 2019-10-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20191016_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='title_text',
            field=models.TextField(default='', verbose_name='Title'),
        ),
    ]
