# Generated by Django 2.2.6 on 2019-10-16 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_video_title_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='title_text',
        ),
    ]
