# Generated by Django 2.2.5 on 2019-10-01 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20191001_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_id',
            field=models.IntegerField(default=0, verbose_name='Video ID'),
        ),
    ]
