# Generated by Django 2.2.6 on 2019-10-16 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0005_remove_video_title_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocomment',
            name='addtime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Add Time'),
        ),
        migrations.CreateModel(
            name='VideoTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('videos', models.ManyToManyField(to='videos.Video')),
            ],
        ),
    ]
