# Generated by Django 2.2.5 on 2019-10-01 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_video_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumb',
            field=models.ImageField(default='no-img.jpg', upload_to='thumbnails/%Y/%m/%d', verbose_name='Thumbnails'),
        ),
        migrations.CreateModel(
            name='VideoThumbnails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumb', models.ImageField(default='no-img.jpg', upload_to='thumbnails/%Y/%m/%d', verbose_name='Thumbnails')),
                ('vid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.Video')),
            ],
        ),
    ]
