# Generated by Django 2.2.5 on 2019-10-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_auto_20191001_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumb_url',
            field=models.CharField(default='/', max_length=200, verbose_name='Thumb URL'),
        ),
    ]
