# Generated by Django 2.2.5 on 2019-09-20 09:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150, verbose_name='Name')),
                ('slug', models.CharField(default='', max_length=120, verbose_name='Slug')),
                ('thumb', models.ImageField(default='no-img.jpg', upload_to='')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AlbumCategory',
                'verbose_name_plural': 'AlbumCategories',
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Name')),
                ('tags', models.TextField(blank=True, verbose_name='Tags')),
                ('total_photos', models.BigIntegerField(default=0, verbose_name='Total photos')),
                ('total_views', models.BigIntegerField(default=0, verbose_name='Total Views')),
                ('type', models.CharField(choices=[('1', 'Public'), ('0', 'Private')], default='1', max_length=1, verbose_name='Type')),
                ('addtime', models.BigIntegerField(default=0, verbose_name='Addtime')),
                ('status', models.CharField(choices=[('0', 'Suspended'), ('1', 'Active')], default='1', max_length=1, verbose_name='Status')),
                ('adddate', models.DateField(default=datetime.date.today, verbose_name='Adddate')),
                ('rate', models.FloatField(default=0, verbose_name='Rate')),
                ('ratedby', models.BigIntegerField(default=0, verbose_name='Ratedby')),
                ('total_comments', models.BigIntegerField(default=0, verbose_name='Total Comments')),
                ('total_favorites', models.BigIntegerField(default=0, verbose_name='Total Favorites')),
                ('likes', models.BigIntegerField(default=0, verbose_name='Likes')),
                ('dislikes', models.BigIntegerField(default=0, verbose_name='Dislikes')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.AlbumCategory')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
            },
        ),
    ]
