# Generated by Django 2.2.5 on 2019-09-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='com_num',
            field=models.IntegerField(default=0),
        ),
    ]
