# Generated by Django 2.2.5 on 2019-09-23 06:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('albums', '0002_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoRatingIp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.IntegerField(default=0, verbose_name='IP')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.Photo')),
            ],
            options={
                'verbose_name': 'PhotoRatingIp',
                'verbose_name_plural': 'PhotoRatingIp',
            },
        ),
        migrations.CreateModel(
            name='PhotoRatingId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.Photo')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PhotoRatingId',
                'verbose_name_plural': 'PhotoRatingId',
            },
        ),
        migrations.CreateModel(
            name='PhotoFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(default='', max_length=15, verbose_name='Reason')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('add_date', models.DateField(default=datetime.date.today, verbose_name='Add Date')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.Photo')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PhotoFlag',
                'verbose_name_plural': 'PhotoFlags',
            },
        ),
        migrations.CreateModel(
            name='PhotoFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.Photo')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PhotoFavorite',
                'verbose_name_plural': 'PhotoFavorite',
            },
        ),
        migrations.CreateModel(
            name='PhotoComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('addtime', models.BigIntegerField(default=0, verbose_name='Addtime')),
                ('status', models.CharField(choices=[('0', 'Suspended'), ('1', 'Active')], default='1', max_length=1, verbose_name='Status')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.Photo')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PhotoComment',
                'verbose_name_plural': 'PhotoComments',
            },
        ),
    ]
