# Generated by Django 2.2.5 on 2019-09-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_com_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='download_num',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='fav_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='featured',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='video',
            name='ratedby',
            field=models.BigIntegerField(default=0, max_length=10),
        ),
    ]
