# Generated by Django 2.2.5 on 2019-10-02 02:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_photocomment_photofavorite_photoflag_photoratingid_photoratingip'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(default='no-img.jpg', upload_to='photo/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='album',
            name='adddate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Adddate'),
        ),
    ]
