# Generated by Django 2.2.5 on 2019-09-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20190909_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='be_comment',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='video',
            name='be_rated',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='video',
            name='embed',
            field=models.CharField(default='enabled', max_length=8),
        ),
        migrations.AddField(
            model_name='video',
            name='embed_code',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='video',
            name='filehome',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='video',
            name='rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='server',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='video',
            name='thumb',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbs',
            field=models.SmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='video',
            name='voter_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
