# Generated by Django 2.2.5 on 2019-09-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20190909_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='active',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='video',
            name='aspect_hd',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='video',
            name='aspect_sd',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='video',
            name='dislikes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='hd',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='hd_filename',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='video',
            name='height_hd',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='height_sd',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='iphone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='ipod_filename',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='video',
            name='likes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='width_hd',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='width_sd',
            field=models.IntegerField(default=0),
        ),
    ]
