# Generated by Django 2.2.5 on 2019-10-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_auto_20191002_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='adddate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Add Date'),
        ),
    ]
