# Generated by Django 2.2.5 on 2019-10-04 03:27

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Title')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content')),
                ('total_views', models.BigIntegerField(default=0, verbose_name='Total Views')),
                ('total_comments', models.BigIntegerField(default=0, verbose_name='Total Comments')),
                ('total_links', models.BigIntegerField(default=0, verbose_name='Total Links')),
                ('addtime', models.BigIntegerField(default=0, verbose_name='Add time')),
                ('adddate', models.DateTimeField(auto_now_add=True, verbose_name='Add Time')),
                ('status', models.CharField(choices=[('0', 'Suspended'), ('1', 'Active')], default='1', max_length=1, verbose_name='Status')),
                ('thumb', models.ImageField(default='no-img.jpg', upload_to='thumbstories/%Y/%m/%d', verbose_name='Thumbnails')),
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Stories',
            },
        ),
        migrations.CreateModel(
            name='StoryComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('addtime', models.BigIntegerField(default=0, verbose_name='Addtime')),
                ('status', models.CharField(choices=[('0', '0'), ('1', '1')], default='1', max_length=1, verbose_name='Status')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.Story')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'StoryComment',
                'verbose_name_plural': 'StoryComments',
            },
        ),
        migrations.CreateModel(
            name='StoryCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150, verbose_name='Name')),
                ('slug', models.CharField(default='', max_length=120, verbose_name='Slug')),
                ('thumb', models.ImageField(default='no-img.jpg', upload_to='')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'StoryCategory',
                'verbose_name_plural': 'StoryCategories',
            },
        ),
        migrations.AddField(
            model_name='story',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.StoryCategory'),
        ),
        migrations.AddField(
            model_name='story',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
