# Generated by Django 2.2.5 on 2019-10-03 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='thumb',
            field=models.ImageField(default='no-img.jpg', upload_to='thumbstories/%Y/%m/%d', verbose_name='Thumbnails'),
        ),
        migrations.AlterField(
            model_name='story',
            name='status',
            field=models.CharField(choices=[('0', 'Suspended'), ('1', 'Active')], default='1', max_length=1, verbose_name='Status'),
        ),
    ]
