# Generated by Django 2.2.6 on 2019-10-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storycomment',
            name='addtime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Add Time'),
        ),
    ]
