# Generated by Django 2.2.5 on 2019-09-24 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190924_1533'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
