# Generated by Django 2.2.5 on 2019-09-20 12:10

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Title')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content')),
                ('total_views', models.BigIntegerField(default=0, verbose_name='Total Views')),
                ('total_comments', models.BigIntegerField(default=0, verbose_name='Total Comments')),
                ('total_links', models.BigIntegerField(default=0, verbose_name='Total Links')),
                ('addtime', models.BigIntegerField(default=0, verbose_name='Add Time')),
                ('adddate', models.DateField(default=datetime.date.today, verbose_name='Add Date')),
                ('status', models.CharField(choices=[('0', 'Suspended'), ('1', 'Active')], default='1', max_length=1, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Notice',
                'verbose_name_plural': 'Notices',
            },
        ),
        migrations.CreateModel(
            name='NoticeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addtime', models.BigIntegerField(default=0, verbose_name='Add Time')),
                ('extension', models.CharField(default='', max_length=5, verbose_name='Extension')),
                ('thumb', models.ImageField(default='no-img.jpg', upload_to='')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'NoticeImage',
                'verbose_name_plural': 'NoticeImages',
            },
        ),
        migrations.CreateModel(
            name='NoticeComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, verbose_name='comment')),
                ('addtime', models.BigIntegerField(default=0, verbose_name='addtime')),
                ('status', models.CharField(choices=[('0', '0'), ('1', '1')], default='1', max_length=1, verbose_name='status')),
                ('nid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notices.Notice')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'NoticeComment',
                'verbose_name_plural': 'NoticeComments',
            },
        ),
        migrations.CreateModel(
            name='NoticeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150, verbose_name='Name')),
                ('slug', models.CharField(default='', max_length=120, verbose_name='Slug')),
                ('thumb', models.ImageField(default='no-img.jpg', upload_to='')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'NoticeCategory',
                'verbose_name_plural': 'NoticeCategories',
            },
        ),
        migrations.AddField(
            model_name='notice',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notices.NoticeCategory'),
        ),
        migrations.AddField(
            model_name='notice',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
